# Generated by Django 4.1.5 on 2023-01-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='purchaser',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='animal',
            name='image_url',
            field=models.URLField(default='https://wildcard.codestuff.io/cat/250/250'),
        ),
    ]
